import type { Grid } from "./types";

/** Complete default grid configuration for the classic Einstein's riddle style. */
export const DEFAULT_CONFIG: Omit<Grid, "size" | "positionLabels"> = {
  categories: [
    {
      name: "Name",
      noun: "",
      subjectPriority: 2,
      values: [
        "Alice",
        "Bob",
        "Carol",
        "Dave",
        "Eve",
        "Frank",
        "Grace",
        "Hank",
      ],
    },
    {
      name: "Color",
      noun: "house",
      verb: ["lives in the", "does not live in the"],
      subjectPriority: -1,
      valueSuffix: "house",
      positionAdjective: ["is", "is not"],
      values: [
        "Red",
        "Blue",
        "Green",
        "Yellow",
        "White",
        "Orange",
        "Purple",
        "Pink",
      ],
    },
    {
      name: "Pet",
      noun: "owner",
      verb: ["owns the", "does not own the"],
      subjectPriority: 1,
      values: [
        "Cat",
        "Dog",
        "Fish",
        "Bird",
        "Rabbit",
        "Turtle",
        "Hamster",
        "Snake",
      ],
    },
    {
      name: "Drink",
      noun: "drinker",
      verb: ["drinks", "does not drink"],
      subjectPriority: 1,
      values: [
        "Tea",
        "Coffee",
        "Water",
        "Milk",
        "Juice",
        "Soda",
        "Wine",
        "Beer",
      ],
    },
    {
      name: "Food",
      noun: "lover",
      verb: ["eats", "does not eat"],
      subjectPriority: 1,
      values: [
        "Pizza",
        "Pasta",
        "Sushi",
        "Tacos",
        "Salad",
        "Steak",
        "Curry",
        "Soup",
      ],
    },
    {
      name: "Hobby",
      noun: "enthusiast",
      verb: ["enjoys", "does not enjoy"],
      subjectPriority: 1,
      values: [
        "Reading",
        "Painting",
        "Knitting",
        "Gardening",
        "Photography",
        "Origami",
        "Pottery",
        "Woodwork",
      ],
    },
    {
      name: "Music",
      noun: "fan",
      verb: ["listens to", "does not listen to"],
      subjectPriority: 1,
      values: [
        "Jazz",
        "Rock",
        "Pop",
        "Blues",
        "Folk",
        "Reggae",
        "Metal",
        "Punk",
      ],
    },
    {
      name: "Sport",
      noun: "player",
      verb: ["plays", "does not play"],
      subjectPriority: 1,
      values: [
        "Soccer",
        "Tennis",
        "Golf",
        "Baseball",
        "Rugby",
        "Cricket",
        "Hockey",
        "Basketball",
      ],
    },
  ],
  positionNoun: ["house", "houses"],
  positionPreposition: "in",
  spatialWords: {
    verb: ["lives", "does not live"],
    adjacency: "next to",
    direction: ["left of", "right of"],
    between: "somewhere between",
    atPosition: ["lives in", "does not live in"],
    cardinals: ["zero", "one", "two", "three", "four", "five", "six", "seven"],
  },
};
